name: PROD CI

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Workaround rollup optional dep (Linux)
        if: runner.os == 'Linux'
        run: npm i -D @rollup/rollup-linux-x64-gnu --no-save

      - name: Check (lint+typecheck+test)
        run: |
          if jq -e '.scripts.check' package.json > /dev/null; then
            npm run check
          else
            echo "No 'check' script; skipping."
          fi

      - name: Build (Vite -> dist/)
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync ./dist s3://sejong-zupzup.kr --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --paths "/*"
